This file allows you to watch wat was said using a comment ID to see if the text make sence

In [2]:
import pandas as pd

In [13]:
data_path = 'Largedata/links2022.ndjson'


data_raw = pd.read_json(data_path, lines=True)

In [16]:
id_list = ['hbjkk9v', 'hm2y3dc', 'eyq3l3x', 'eyq5tm8', 'eyvo9tt', 'ezlthpn', 'ezlzq7r', 'ezqmt0c', 'eztdlbr', 'ezulygq', 'f0nhlz4', 'f0nwv81', 'f0pdu21', 'f0v4qy4', 'f169ntx', 'f1oogd7', 'f1x43gv', 'f26bfd6', 'f299p56', 'f299vxt', 'f299x19', 'f2xjm9x', 'f32f0kb', 'f32f5cy', 'f32ffw6', 'f32fng0', 'f32fxmw', 'f33iu0d', 'f363lyp', 'f4j6elg', 'f5yb25m', 'f6rajiz', 'f8ri9x5', 'f8rj6c8', 'f8rnqmd', 'f8rrb1f', 'f9z85uz', 'ff9wr20', 'fiz58t1', 'fj7oyzr', 'fj96u37', 'fj9xz1y', 'fjmrics', 'fma81hg', 'fne6f72', 'fnoo3h0', 'fnooqa9', 'fnop9s3', 'fnoplku', 'fnzdei1', 'fomcae4', 'fqopqv1', 'fslgap7', 'fslvbj6', 'fy0fs3n', 'g0fcd9x', 'gii8vk6', 'giibe0x', 'gmlyoyp', 'gva3s4e', 'gx900j6', 'gxy64k9', 'gz11qxw', 'hcpc56g', 'hcpdmgi', 'hegj0wz', 'hegk4pj', 'hegsfdz', 'hfhv0xq', 'hfhv37z', 'hfn72sx', 'hglr6wh', 'hglra3u', 'hgnprg5', 'hjl3vvt', 'hk31hmn', 'hk39qis', 'hkb35t3', 'hkb3bdb', 'hkb3pcn', 'hkbkcbu', 'hkbl7hr', 'hl62x4t', 'hlqud5h', 'hlreclo', 'hlreeml', 'hlrqip5', 'hlvi9ga', 'hlxtcdj', 'hm7bf0u', 'hmb17d6', 'hmfv075', 'hmnjkhr', 'hms9ja3', 'hmsajdn', 'hmseum1', 'hmwn05h', 'hmygkz4', 'hn2ueki', 'hnvacll', 'hnvq6qo', 'ho3rog1', 'homwt11', 'hpcuto8', 'hpozjw6', 'hppcorh', 'hppell5', 'hpqcngp', 'hq9gmxm', 'hq9n8z9', 'hqbmdkn']
#Remove all rows not where the id is in the id_list
data = data_raw[data_raw['id'].isin(id_list)]
data

,out_going,in_going,id,flair,comment
242877,tumblerrjin,None,hbjkk9v,entp,Bee is accurate.
254107,Frequent-Candidate42,None,hcpc56g,entp,We all know ENTP is the best.
254116,Frequent-Candidate42,ENFJohn,hcpdmgi,entp,I had 2 infp bestfriends and unfortunately our...
269786,Frequent-Candidate42,Salmonella1984,hegj0wz,entp,I was mistyped as INTP and when I discovered t...
269791,Frequent-Candidate42,None,hegk4pj,entp,MBTI and astrology are different things! \n\nA...
...,...,...,...,...,...
1037751,tumblerrjin,None,gmlyoyp,entp,I had no idea this had anything to do with per...
1111847,tumblerrjin,None,gva3s4e,entp,I think we belong in the top area. Because of ...
1127719,tumblerrjin,None,gx900j6,entp,I feel so understood when someone explains dif...
1133285,tumblerrjin,None,gxy64k9,entp,Egg
1142474,tumblerrjin,None,gz11qxw,entp,"I married an ISFJ, a wonderful amazing creatur..."

In [11]:
data

Empty DataFrame
Columns: [out_going, in_going, id, flair, comment]
Index: []